version: '3.7'

x-service-base: &service-base
     init: true

volumes:
  wp-volume:
    driver: local
    name: wp-volume
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/${USER}/data/wordpress'

  db-volume:
    driver: local
    name: db-volume
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/${USER}/data/mariadb'

services:
  mariadb:
    <<: *service-base
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    env_file: .env_db
    volumes:
      - db-volume:/var/lib/mysql:rw
    networks:
      - inception
    restart: unless-stopped
    expose:
      - "3306"

  nginx:
    <<: *service-base
    depends_on:
      - wordpress
    container_name: nginx
    volumes:
      - wp-volume:/var/www/wordpress
    networks:
      - inception
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    <<: *service-base
    depends_on:
      - mariadb
    env_file: .env_wp
    container_name: wordpress
    volumes:
      - wp-volume:/var/www/wordpress
    networks:
      - inception
    build:
      context: ./requirements/wordpress
    restart: on-failure
    expose:
      - "9000"

networks:
    inception:
      driver: bridge
